# Generated by Django 5.2.3 on 2025-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_utilisateur_mot_de_passe_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('drh', 'DRH'), ('directeur', 'Directeur Pays'), ('collaborateur', 'Collaborateur'), ('ca', 'Chef Antenne'), ('cp', 'Chef Projet')], default='collaborateur', max_length=20),
        ),
    ]
