# Generated by Django 5.2.3 on 2025-06-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_annee_mois'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mois',
            options={'ordering': ['mois']},
        ),
        migrations.AlterUniqueTogether(
            name='mois',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mois',
            name='mois',
            field=models.CharField(choices=[('01', 'Janvier'), ('02', 'Février'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Août'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='mois',
            unique_together={('mois', 'annee')},
        ),
    ]
