# Generated by Django 5.2.3 on 2025-07-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0006_alter_absence_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='solde_initial',
            field=models.IntegerField(blank=True, default=0, help_text='Solde de congé initial (sera utilisé à la création uniquement)'),
        ),
    ]
