name: Build and deploy Python app to Azure Web App - gestionabsences

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SECRET: ${{ secrets.SECRET }}  # Injection globale de la variable SECRET

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Vérification de la variable SECRET
        run: |
          if [ -z "$SECRET" ]; then
            echo "❌ SECRET n'est pas définie !"
            exit 1
          else
            echo "✅ SECRET est bien définie."
          fi

      - name: Create and activate virtual environment, install dependencies, and collect static files
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py collectstatic --noinput --settings=gestion_absences.deployment

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "*.git*" "*.github*" "__pycache__/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'gestionabsences'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_90446C04DFB14A9FAE8C46E950969FB7 }}
